[package]
name = "onion"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = "1.5.0"
nom = "7.1.3"
rand = "0.9.2"
clap = { version = "4.5", features = ["derive"] }
rustyline = "14.0"
minifb = "0.28.0"
image = "0.24"
rodio = "0.17"
font8x8 = "0.3"
